additionalTrustBundlePolicy: Proxyonly
apiVersion: v1
baseDomain: devcluster.openshift.com
compute:
- architecture: amd64
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: 0
controlPlane:
  architecture: amd64
  hyperthreading: Enabled
  name: master
  platform:
    aws:
      rootVolume:
        size: 64
      type: r5.2xlarge
  replicas: 1
metadata:
  creationTimestamp: null
  name: redpod-aws-sno
networking:
  clusterNetwork:
  - cidr: 10.128.0.0/14
    hostPrefix: 23
  machineNetwork:
  - cidr: 10.0.0.0/16
  networkType: OVNKubernetes
  serviceNetwork:
  - 172.30.0.0/16
platform:
  aws:
    region: us-west-2
publish: External
pullSecret: '{"auths":{"cloud.openshift.com":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYzZiMjdhMjA5MzI1NDY4ZGEyNGNhNmU1ZmE4MGQwOTg6U0pYRDQ2R05MN0Y5VFAxN1lIMjBIM1RQRDJaMUNZVU5ZUUJHS0tJMzA2M0FROUU1RVc0QTFLUldNUTRFVVUwNQ==","email":"jufaerma@redhat.com"},"quay.io":{"auth":"b3BlbnNoaWZ0LXJlbGVhc2UtZGV2K29jbV9hY2Nlc3NfYzZiMjdhMjA5MzI1NDY4ZGEyNGNhNmU1ZmE4MGQwOTg6U0pYRDQ2R05MN0Y5VFAxN1lIMjBIM1RQRDJaMUNZVU5ZUUJHS0tJMzA2M0FROUU1RVc0QTFLUldNUTRFVVUwNQ==","email":"jufaerma@redhat.com"},"registry.connect.redhat.com":{"auth":"fHVoYy1wb29sLWVlZDUyZjc1LTkyMGQtNDhjMy1iM2VhLTNkNGFlOTM2ODBjMzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdPR1V6TXpGa1pqRTNaRFkwTVRsa1lUSmpNMlk1TUdFeE1qQmlORFUzWVNKOS5aeS1RWk83TV9uV3daSHQ4STJpck5uMkFob0ZyU1g0SnBsc1lMcV92T2NDLWYyN1VscTN6NkhzN0xwN3dfWlQ2R05oaHZVc3R0eFk4aTd3eFlwNnZGcEJrelgxOFlFc01Mc3l6Wnl5TGl0YmYtU2E5VHZ6M1pmYnBSVmVGTXlxcVBpRnhLR21fNW10ZTd6dlBIcHRHYl9FQTlBbU5XMnpQQ3gtVE1rTTl6bGhwZ2NGcTF3NWhqdVlqRzN3alhqa0RoZjZ5Wmd5dUs1LWFKNzdwTGtnMVFBRG4xM2MxWHhRQ0xkVkNFSU1tTG55STlyZlNWX1FuSk1Lekp3MHdRbTBLdThRT2NHX2xMb0lfbW12MVZfSFQyX0NRTno0ZVp0VnM1UG80am0zUEtYblRodjVKanRBQ2tKbVdHdXlZUjU5YmJTMGx3al9UVHE0Z2ZCYkt1bWx5MDFaZnJnOXZaRHdCbWRjZ2wzT2F4Q2NuX3BlblZ2TnJTT3JqOXhheGN2VEs3dkg2OUFhenpkdEx6UTNfU0l4R1lzLWVlMkMyMl9EdTUwQXA2Y1dkY09XSzZTUDlqSERKRjV5SW1PeXRBY1NJem9nTFhHZFRSQ3BmZUJFWlZGVnNFbUZ2X29DV3ZQUFdGek5HdWRoRTdWY2FhX2RCT0o0c21MaTY5SkRieEtISUw1bHRQNlI2cGxWTGpma1N2WkRMNzFvVmo4bnhrMkxSVjcxbVBxUFhoRTFkaGgtdVBTM1FKeW02aWQ5SUdqMHZncDFFYnBrSXJuOTdxY1BSMFhaWFQ5WkdkQ19qdGlVbW5mcGVPQVdxOXpmcmlpWk5UZ2VJbU56aVdkVWNJLVBldWZaMHhNNkxwTFVZVlIwNG15UlBqZTNmNHlZUXpfLTB1V0dzMkJVdEtqWQ==","email":"jufaerma@redhat.com"},"registry.redhat.io":{"auth":"fHVoYy1wb29sLWVlZDUyZjc1LTkyMGQtNDhjMy1iM2VhLTNkNGFlOTM2ODBjMzpleUpoYkdjaU9pSlNVelV4TWlKOS5leUp6ZFdJaU9pSXdPR1V6TXpGa1pqRTNaRFkwTVRsa1lUSmpNMlk1TUdFeE1qQmlORFUzWVNKOS5aeS1RWk83TV9uV3daSHQ4STJpck5uMkFob0ZyU1g0SnBsc1lMcV92T2NDLWYyN1VscTN6NkhzN0xwN3dfWlQ2R05oaHZVc3R0eFk4aTd3eFlwNnZGcEJrelgxOFlFc01Mc3l6Wnl5TGl0YmYtU2E5VHZ6M1pmYnBSVmVGTXlxcVBpRnhLR21fNW10ZTd6dlBIcHRHYl9FQTlBbU5XMnpQQ3gtVE1rTTl6bGhwZ2NGcTF3NWhqdVlqRzN3alhqa0RoZjZ5Wmd5dUs1LWFKNzdwTGtnMVFBRG4xM2MxWHhRQ0xkVkNFSU1tTG55STlyZlNWX1FuSk1Lekp3MHdRbTBLdThRT2NHX2xMb0lfbW12MVZfSFQyX0NRTno0ZVp0VnM1UG80am0zUEtYblRodjVKanRBQ2tKbVdHdXlZUjU5YmJTMGx3al9UVHE0Z2ZCYkt1bWx5MDFaZnJnOXZaRHdCbWRjZ2wzT2F4Q2NuX3BlblZ2TnJTT3JqOXhheGN2VEs3dkg2OUFhenpkdEx6UTNfU0l4R1lzLWVlMkMyMl9EdTUwQXA2Y1dkY09XSzZTUDlqSERKRjV5SW1PeXRBY1NJem9nTFhHZFRSQ3BmZUJFWlZGVnNFbUZ2X29DV3ZQUFdGek5HdWRoRTdWY2FhX2RCT0o0c21MaTY5SkRieEtISUw1bHRQNlI2cGxWTGpma1N2WkRMNzFvVmo4bnhrMkxSVjcxbVBxUFhoRTFkaGgtdVBTM1FKeW02aWQ5SUdqMHZncDFFYnBrSXJuOTdxY1BSMFhaWFQ5WkdkQ19qdGlVbW5mcGVPQVdxOXpmcmlpWk5UZ2VJbU56aVdkVWNJLVBldWZaMHhNNkxwTFVZVlIwNG15UlBqZTNmNHlZUXpfLTB1V0dzMkJVdEtqWQ==","email":"jufaerma@redhat.com"}}}'
sshKey: |
  ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUrDu6U+4/PxPYH0gyPTi5onqeyeqmwgKXeh8qTee6XJ3Zbk0uJtMbb0x0VrkZqao8+8raz+FOT+AbbEjjxMb1+C4QLC6EmDrCMTLsWiI+yHlxH+g9FO5v+g5hUQe6MtzHdwjD29k0zC5ADh2xWWcz0nwZ9borhYUF3XaRBB6yN2DeB+Hex/zN7geueVxIt8zadqtaEqvgFrjPP9cXjijz4+QwOjlU+OGYp9IYsnMmGC55AFPeEhKiFWG1DoEfls3DBJaWE3E8emCjEP49q9ZMwJDAf2RgkKJbylq8c2b/R4JQEBP7YqDUzMkYjf+BH8u9aeggL5oGTJUKkJVGoQZQyjCYg899lVTx5aPwwpZTtMc0tAZpewMVc2VpaiGLVYRnMqLwBGVveD5iMU4irXDdYWGB1M3BLZIfNGxfWrbpKPCtl2+t8DF5FDQMMtoQdzop9sU2Z3TJsNI3iPP2jjA74jy9aZJMwqzzWOyGoMGtSsecdWxYaeMSRysHdBTGC2k= faermanj@fedora
