# gitpod.io/#github.com/CaravanaCloud/red-pod
image:
  file: .gitpod.Dockerfile

tasks:
  - name: docker compose
    command: docker-compose -f .gitpod/docker-compose-gitpod.yml up -d --build
  
  - name: mysql
    command: docker logs -f mysql

  - name: mysql-client
    command: mysql -h127.0.0.1 -P3306 -uroot -pMasterkey123 redpoddb

  - name: keycloak
    command: docker logs -f keycloak


ports:
  - port: 3300
    onOpen: ignore
    visibility: public

  - port: 3306
    onOpen: ignore
    visibility: public

  - port: 5000
    onOpen: ignore
    visibility: public

  - port: 5005
    onOpen: ignore
    visibility: public

  - port: 8080
    onOpen: open-browser
    visibility: public

  - port: 8081
    onOpen: open-browser
    visibility: public

  - port: 8888
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - redhat.fabric8-analytics
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
#    - GitHub.copilot

