# gitpod.io/#github.com/CaravanaCloud/red-pod
image:
  file: .gitpod.Dockerfile

tasks:
  - name: shell
    command: echo "this shell is yours to use"

  - name: set environment variables
    before: |
      gp env OCP_CLUSTER_NAME=rhnb-ocp-cluster
      gp env OCP_WORKER_ARCH=amd64
      gp env OCP_WORKER_REPLICAS=3
      gp env OCP_MASTER_ARCH=amd64
      gp env OCP_MASTER_REPLICAS=3
      gp env OCP_CLUSTER_NET_CIDR=10.128.0.0/14
      gp env OCP_CLUSTER_NET_HOST_PREFIX=23
      gp env OCP_MACHINE_NET_CIDR=10.0.0.0/16
      gp env OCP_SERVICE_NET_CIDR=172.30.0.0/16
      gp env OCP_AWS_REGION=ap-northeast-1
      eval $(gp env -e)


  - name: docker pull and up
    init: docker-compose -f .gitpod/docker-compose-gitpod.yml pull 
    command: >
      docker-compose -f .gitpod/docker-compose-gitpod.yml up -d --build && 
      gp sync-done compose-up
  
  - name: mysql
    command: >
      gp sync-await compose-up && 
      docker logs -f mysql

  - name: mysql-client
    command: > 
      gp await-port 3306 && 
      sleep 30 &&
      mysql -h127.0.0.1 -P3306 -uroot -pMasterkey123 redpoddb

  - name: keycloak
    command: >
      gp sync-await compose-up && 
      docker logs -f keycloak

  - name: jupyter
    command: cd jupyter && gp open index.ipynb && jupyter notebook --no-browser
  
  - name: temp ssh
    command: |
        rm -rf "/tmp/temp_ssh"
        ssh-keygen -b "2048" -t "ed25519" -f "/tmp/temp_ssh" -q -N ""
        ls -l "/tmp/temp_ssh"*

ports:
  - port: 3300
    onOpen: ignore
    visibility: public

  - port: 3306
    onOpen: ignore
    visibility: public

  - port: 5000
    onOpen: ignore
    visibility: public

  - port: 5005
    onOpen: ignore
    visibility: public

  - port: 8080
    onOpen: ignore
    visibility: public

  - port: 8081
    onOpen: open-browser
    visibility: public

  - port: 8888
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - ms-azuretools.vscode-docker
    - ms-python.python
    - ms-toolsai.jupyter
    - esbenp.prettier-vscode
#    - redhat.fabric8-analytics
#    - GitHub.copilot

