# gitpod.io/#github.com/CaravanaCloud/red-pod
image:
  file: .gitpod.Dockerfile


ports:
  - port: 5000
    onOpen: ignore
    visibility: public

  - port: 8080
    onOpen: ignore
    visibility: public

  - port: 8888
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - vscjava.vscode-java-debug
    - vscjava.vscode-java-dependency
    - vscjava.vscode-java-test
    - vscjava.vscode-maven
    - redhat.java
    - redhat.fabric8-analytics
    - ms-azuretools.vscode-docker
    - esbenp.prettier-vscode
#    - GitHub.copilot

