apiVersion: v1
baseDomain: $OCP_BASE_DOMAIN

compute:
- architecture: $OCP_WORKER_ARCH
  hyperthreading: Enabled
  name: worker
  platform: {}
  replicas: $OCP_WORKER_REPLICAS

controlPlane:
  architecture: $OCP_MASTER_ARCH
  hyperthreading: Enabled
  name: master
  platform: {}
  replicas: $OCP_MASTER_REPLICAS

metadata:
  creationTimestamp: null
  name: $OCP_CLUSTER_NAME
networking:
  clusterNetwork:
  - cidr: $OCP_CLUSTER_NET_CIDR
    hostPrefix: $OCP_CLUSTER_NET_HOST_PREFIX
  machineNetwork:
  - cidr: $OCP_MACHINE_NET_CIDR
  networkType: OpenShiftSDN
  serviceNetwork:
  - $OCP_SERVICE_NET_CIDR
platform:
  aws:
    region: $OCP_AWS_REGION
publish: External
pullSecret: '$PULL_SECRET'
